# frozen_string_literal: true

require 'lib/topology_builder/csv_mapper/table_base'

RSpec.describe NetomoxExp::TopologyBuilder::CSVMapper do
  # expose protected helpers of TableRecordBase
  let(:record) do
    Class.new(described_class::TableRecordBase) do
      public :parse_array_string, :true_string?, :extract_interfaces
    end.new
  end

  describe '#parse_array_string' do
    it 'returns [] for nil or empty string' do
      expect(record.parse_array_string(nil)).to eq []
      expect(record.parse_array_string('')).to eq []
    end

    it 'parses ruby/json style array string' do
      expect(record.parse_array_string('["a","b","c"]')).to eq %w[a b c]
      expect(record.parse_array_string('[]')).to eq []
    end

    it 'splits comma separated numbers (bgp confederation members)' do
      expect(record.parse_array_string('65001,65002')).to eq %w[65001 65002]
      expect(record.parse_array_string('65001')).to eq ['65001']
    end

    it 'raises error for string that is not array style' do
      expect { record.parse_array_string('foo') }.to raise_error(StandardError, /Not array style string/)
    end
  end

  describe '#true_string?' do
    it 'is case-insensitive' do
      expect(record.true_string?('True')).to be true
      expect(record.true_string?('true')).to be true
      expect(record.true_string?('False')).to be false
    end
  end

  describe '#extract_interfaces' do
    it 'converts "[node1[intf1], node2[intf2]]" to edge objects' do
      edges = record.extract_interfaces('[site-a-br-1[ge-0/0/2], site-a-br-2[ge-0/0/2]]')
      expect(edges.map(&:to_s)).to eq %w[site-a-br-1[ge-0/0/2] site-a-br-2[ge-0/0/2]]
      expect(edges.map(&:node)).to eq %w[site-a-br-1 site-a-br-2]
      expect(edges.map(&:interface)).to eq %w[ge-0/0/2 ge-0/0/2]
    end
  end

  describe 'EdgeBase' do
    it 'can be generated by node and interface names and compared' do
      edge = described_class::EdgeBase.generate('r1', 'ge-0/0/0')
      expect(edge.to_s).to eq 'r1[ge-0/0/0]'
      expect(edge).to eq described_class::EdgeBase.new('r1[ge-0/0/0]')
      expect(edge).not_to eq described_class::EdgeBase.new('r1[ge-0/0/1]')
    end
  end
end
