version: "3"
services:
  netoviz:
    image: netoviz/allinone
    ports:
      - "3000:3000"
    volumes:
      - ./netoviz_model:/home/netoviz/static/model
  batfish:
    image: "batfish/allinone"
    container_name: "batfish"
    ports:
      - "9996:9996"
      - "9997:9997"
  netomox:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - BATFISH_HOST=192.168.23.32
      - GEM_PATH=/myapp
    volumes:
      - .:/myapp
    command:   bash -c "cd /myapp &&bundle install --path=vendor/bundle && bundle exec rake"
