# frozen_string_literal: true

require 'netomox'
require_relative 'verifier_base'

module NetomoxExp
  # bgp-proc verifier
  class BgpProcVerifier < VerifierBase
    # @param [String] severity Base severity
    def verify(severity)
      verify_according_to_links
      verify_according_to_nodes
      @log_messages.filter { |msg| msg.upper_severity?(severity) }.map(&:to_hash)
    end

    private

    # @param [Netomox::Topology::TpRef] edge Link edge
    # @return [Array(Netomox::Topology::Node, Netomox::Topology::TermPoint)]
    def find_node_tp_by_edge(edge)
      bgp_proc_node = @bgp_proc_nw.find_node_by_name(edge.node_ref)
      bgp_proc_tp = bgp_proc_node.find_tp_by_name(edge.tp_ref)
      [bgp_proc_node, bgp_proc_tp]
    end

    # @param [Netomox::Topology::TermPoint] src_tp Source term-point
    # @param [Netomox::Topology::TermPoint] dst_tp Destination term-point
    # @return [String] link name which connects src/dst term-points
    def tps_to_link_name(src_tp, dst_tp)
      [src_tp.parent_name, src_tp.name, dst_tp.parent_name, dst_tp.name].join(',')
    end

    # @param [Netomox::Topology::TermPoint] src_tp Source term-point
    # @param [Netomox::Topology::TermPoint] dst_tp Destination term-point
    # @return [void]
    def verify_peer_asn_ip(src_tp, dst_tp)
      # alias
      stp_attr = src_tp.attribute
      dtp_attr = dst_tp.attribute

      # NOTE: check src_tp.remote_as/ip == dst_tp.local_as/ip
      #   will be check src_tp.local_as/ip == dst_tp.remote_as/ip in reverse-link (bidirectional link)

      # NOTE: switch dst local_as when confederation config is not equal
      dst_local_as = dtp_attr.local_as
      if stp_attr.confederation != dtp_attr.confederation && dtp_attr.confederation.positive?
        dst_local_as = dtp_attr.confederation
      end

      return if stp_attr.remote_as == dst_local_as && stp_attr.remote_ip == dtp_attr.local_ip

      add_log_message(:error, tps_to_link_name(src_tp, dst_tp), 'ASN/IP does not correspond')
    end

    # @param [Netomox::Topology::TermPoint] src_tp Source term-point
    # @param [Netomox::Topology::TermPoint] dst_tp Destination term-point
    # @return [void]
    def verify_timer(src_tp, dst_tp)
      return if src_tp.attribute.timer == dst_tp.attribute.timer

      add_log_message(:error, tps_to_link_name(src_tp, dst_tp), 'Timer params does not correspond')
    end

    # @param [Netomox::Topology::Link] link A link of bgp_proc network
    # @return [void]
    def verify_link_pair(link)
      # NOTE: search pair (reverse) link, because bgp-proc layer is spliced two topologies:
      #   one is external-AS topology: generated by hand-written...MUST be checked
      #   another one is internal-AS topology: generated from config-files.

      # search pair (reverse) link
      return if @bgp_proc_nw.find_link(link.destination, link.source)

      add_log_message(:error, link.name, 'Reverse link is not found')
    end

    # @param [Netomox::Topology::Link] link A link of bgp_proc network
    # @return [void]
    def verify_peer_params(link)
      _, src_tp = find_node_tp_by_edge(link.source)
      _, dst_tp = find_node_tp_by_edge(link.destination)
      verify_peer_asn_ip(src_tp, dst_tp)
      verify_timer(src_tp, dst_tp)
    end

    # @return [void]
    def verify_according_to_links
      @bgp_proc_nw.links.each do |bgp_proc_link|
        verify_link_pair(bgp_proc_link)
        verify_peer_params(bgp_proc_link)
      end
    end

    # @param [Netomox::Topology::Node] node A node of bgp_proc network
    # @param [Netomox::Topology::TermPoint] term_point A term-point of the node
    # @return [void]
    def verify_unlinked_tp(node, term_point)
      return if @bgp_proc_nw.find_link_by_source(node.name, term_point.name)

      add_log_message(
        :warn,
        "#{node.name}[#{term_point.name}]",
        'Standalone peer config (does not connected)'
      )
    end

    # @return [void]
    def verify_according_to_nodes
      @bgp_proc_nw.nodes.each do |bgp_proc_node|
        bgp_proc_node.termination_points.each do |bgp_proc_tp|
          verify_unlinked_tp(bgp_proc_node, bgp_proc_tp)
        end
      end
    end
  end
end
